### ISSUE TITLE
Integrating icomplete-vertical into core Emacs

### ISSUE THREAD

**Issue by phikal** [oantolin/icomplete-vertical#14]
Hi,

there have been some discussions on the mailing list recently on integrating `icomplete-vertical`  into core Emacs. 

As fas as I see, there are two significant contributors (you and @protesilaos) that would require a copyright assignment, which shouldn't be too difficult.

There's a discussion going on here: https://lists.gnu.org/archive/html/emacs-devel/2020-06/msg00375.htm, if you'd like to join in or have any other questions.

Would be happy to see your package bundled in by default.

**Comment by manuel-uberti** [comment]
@oantolin 

> Copyright assignment is a simple process. Residents of some countries can do it entirely electronically. We can help you get started, including sending you the forms you should fill, and answer any questions you may have (or point you to the people with the answers), at the emacs-devel@gnu.org mailing list.

 

From: https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html

**Comment by oantolin** [comment]
That mysterious paragraph is all the information I managed to find too, @manuel-uberti. I guess I have to write to the emacs-devel list if I want to actually find out.

**Comment by protesilaos** [comment]
Check this instead: https://git.savannah.gnu.org/cgit/gnulib.git/tree/doc/Copyright/request-assign.future

The name of the program just needs to be "Emacs"

**Comment by basil-conto** [comment]
If anyone's interested in the slightly more detailed CA spiel from a maintainer's PoV, it's at:

https://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html

or, if you have this manual installed locally, e.g. via the `gnulib` Debian package, at:

`(info "(maintain) Copyright Papers")`

**Comment by dgutov** [comment]
In the meantime, @Ergus has been working on reimplementing this feature in the core.

Anybody interested should check out the `feature/icomplete-vertical` branch.

**Comment by oantolin** [comment]
That's great news, @dgutov ! Thanks to @ergus for picking up the ball I dropped! I've been swamped at work for a while now and am glad to see someone else do this.

**Comment by protesilaos** [comment]
Thank you @oantolin for all your contributions!

A couple of questions @Ergus, as I have never done this before:

1. How does one test it? Do I need to re-compile Emacs with that specific branch or is there some other way?  I currently am on the `master` branch.
2. What is the right place to discuss this?  emacs-devel?

**Comment by phikal** [comment]
Protesilaos Stavrou <notifications@github.com> writes:

> 1. How does one test it? Do I need to re-compile Emacs with that
> specific branch or is there some other way?  I currently am on the
> `master` branch.

You could just check-out the branch, and load the changed files, but
you'd have to do that every time you start you're local Emacs.

> 2. What is the right place to discuss this?  emacs-devel?

There's a thread on the subject on emacs-devel.

-- 
	Philip K.

**Comment by protesilaos** [comment]
Thank you @phikal!

**Comment by manuel-uberti** [comment]
FWIW, I've checked out the mentioned branch today to give it a spin and it seems on the right track. Let's thank @Ergus for this. :)

**Comment by phikal** [comment]
This has been added over a year ago, so this issue can be closed.
