### ISSUE TITLE
default candidate at the top

### ISSUE THREAD

**Issue by minad** [oantolin/icomplete-vertical#17]
selectrum has an option no-move-default-candidate which ensures that the default candidate is *not* moved to the top. This is used by consult-line if selectrum is active. Is something like this possible in icomplete-vertical too?

**Comment by oantolin** [comment]
To confirm, I'll have to look into exactly what that means in selectrum, but I think the answer is that icomplete has nothing like that, and therefore neither does icomplete-vertical which is supposed to change only the appearance of icomplete.

**Comment by minad** [comment]
Ok, cool. I thought I just ask. It is not an important feature. consult-line still works well with icomplete without that.
