### ISSUE TITLE
Bleeding prompt

### ISSUE THREAD

**Issue by minad** [oantolin/icomplete-vertical#20]
Icomplete-vertical has the same prompt bleeding issue as Selectrum had. See https://github.com/raxod502/selectrum/issues/235. @clemera fixed this in https://github.com/raxod502/selectrum/pull/413.

**Comment by oantolin** [comment]
OK, it seems it does suffer from the bleeding prompt problem:

```elisp
(completing-read (propertize "Candidates: " 'face '(:background "purple"))
                 (list
                  (propertize "GNU" 'display "some-prefix: GNU")
                  (propertize "Emacs" 'display "other-prefix: Emacs")))
```

Now I'll go read the fix.

**Comment by oantolin** [comment]
Ah, OK, it's just about flattening the display properties into the string. I'll just steal @clemera's function, then.

**Comment by minad** [comment]
Thanks for the fix!

**Comment by oantolin** [comment]
I just realized that now icomplete-vertical doesn't have this bug but icomplete still does... 🙄

**Comment by minad** [comment]
Have fun reporting it upstream! Btw, there is also a recursive icomplete bug, where Icomplete does not update the display, when pressing `M-x C-x o M-x C-g` (Selectrum had that bug too, but @clemera just fixed it). You may also want to fix that in icomplete-vertical only :laughing:

**Comment by clemera** [comment]
@oantolin Maybe just post another message to https://debbugs.gnu.org/cgi/bugreport.cgi?bug=46177 and CC Eli in the threat there? I forgot to mention that and that might have been a more convincing example that it is worth looking into it.
