### ISSUE TITLE
[Bug] void-variable display

### ISSUE THREAD

**Issue by rprimus** [oantolin/icomplete-vertical#22]
Tue Feb  9 10:04:34 GMT 2021

Since https://github.com/oantolin/icomplete-vertical/commit/1372ef096297e5f92f08be8dd43ec8cc6b6b85a4 I am getting the following error (in the minibuffer) when using the minibuffer:

```
Error in post-command-hook (icomplete-post-command-hook): (void-variable display)
```

Disabling `icomplete-vertical` allows normal operation.

![icomplete-error](https://user-images.githubusercontent.com/278414/107349386-13008b80-6ac0-11eb-9c16-c0caab81e9ec.gif)

**Comment by oantolin** [comment]
What version of Emacs are you using?

**Comment by basil-conto** [comment]
In order to use `if-let*` you need `(eval-when-compile (require 'subr-x))`.

**Comment by rprimus** [comment]
Tue Feb  9 12:53:56 GMT 2021

System info:

ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H512

"GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, Carbon Version 162 AppKit 1894.6) of 2020-11-15"

icomplete-vertical-20210208.130/

**Comment by oantolin** [comment]
> In order to use `if-let*` you need `(eval-when-compile (require 'subr-x))`.

Thanks @basil-conto! Most of my packages do, I forgot this one doesn't. And I only tested on my system which has many common libraries loaded all the time.

**Comment by oantolin** [comment]
I'm not sure the issue @basil-conto pointed out is actually the problem here, but I fixed that. c7d96c57c66fa01dd1fbf9df64a619b0f8741193

Please test, @rprimus.

**Comment by minad** [comment]
@oantolin I wonder if you would see the problem via flycheck/flymake if you enable this package lint package. I am having this on all the time when editing lisp packages and haven't seen downsides, except that it is slow when you open files like org.el. But this is something I only do for benchmarking 😆

**Comment by rprimus** [comment]
> Please test

The error message is gone.

Just FYI - these are the errors/warnings when `icomplete-vertical` is installed:

```
In icomplete-vertical--display-string:
icomplete-vertical.el:171:44:Warning: ‘(display (get-text-property pos
    'display str))’ is a malformed function
icomplete-vertical.el:178:26:Warning: reference to free variable ‘display’

In end of data:
icomplete-vertical.el:349:1:Warning: the function ‘if-let*’ is not known to be
    defined.
```

**Comment by oantolin** [comment]
Out of the three error messages, you picked the least informative one to put in the title! 😆 I'm lucky @basil-conto was around to figure this out.
