### ISSUE TITLE
Add support for affixation-function

### ISSUE THREAD

**Issue by minad** [oantolin/icomplete-vertical#24]
See also https://github.com/oantolin/embark/issues/169

**Comment by oantolin** [comment]
I won't do this until I can easily install an Emacs that has it. I'd be nervous to add a feature I am unable to test.

**Comment by oantolin** [comment]
Well, you don't use an Emacs with affixations either, what do you do to test?

**Comment by minad** [comment]
Marginalia generates affixation functions and they are picked up by Selectrum. It works, but I don't have any Emacs built-in affixations :shrug:

**Comment by oantolin** [comment]
Right, so you haven't tested that, for example, the built-in affixations have the type you expected or that they are OK running in whatever buffer you run them, etc. I guess I could go with that wild-west strategy and fix bugs with the built-in affixations when I have access to them.

**Comment by minad** [comment]
Actually I thought the spec is simply enough to do the wild-west approach. @clemera seems to agree :cowboy_hat_face:
