### ISSUE TITLE
Replace icomplete-vertical-do by advice?

### ISSUE THREAD

**Issue by minad** [oantolin/icomplete-vertical#26]
I believe local icomplete-vertical configuration is better solved by an `:around` advice. This way the command definition is independent of icomplete-vertical and can be configured for icomplete afterwards. The idea is similar to `consult-config`. Advising a command less general assuming you have multiple `completing-read` sessions, so maybe both the macro and an advice function would be justified.

**Comment by oantolin** [comment]
Maybe it's even better to just remove it?

**Comment by minad** [comment]
Yes, I agree. It is probably better to not provide it, I just wasn't bold enough to propose it. If users really need this, they can write  wrappers themselves which reconfigure the completion system locally.

**Comment by oantolin** [comment]
I'll bite the bullet and outright remove it and deal with complaints (which probably won't even come) by explaining how to use advice for this purpose.

**Comment by oantolin** [comment]
Mmh. I need to think about it a bit more. It seems the macro helps out quite a bit. It uses `unwind-protect` to ensure `icomplete-vertical` is deactivated even if there is an error or the user quits, people would probably have to do that in their functions. It also handles the (over-engineered 😢) system to configure the separator: if you want to set the separator by name a simple `let` won't suffice.
