### ISSUE TITLE
Rendering bug with x-group-function

### ISSUE THREAD

**Issue by minad** [oantolin/icomplete-vertical#29]
![bug](https://user-images.githubusercontent.com/50754/112721110-71fc5180-8f02-11eb-9d8d-e3b354d498d1.png)

This bug is probably due to how the group header is injected into the candidate list. Maybe there is a better way to solve this.

**Comment by oantolin** [comment]
I guess even attaching the heading to the previous candidate would be an improvement.

**Comment by oantolin** [comment]
Except of course that the first heading has no previous candidate.

**Comment by oantolin** [comment]
It look like using `line-prefix` instead of `display` fixes this!

**Comment by minad** [comment]
It seems that this may have introduced another bug? https://github.com/minad/consult/issues/278
