### ISSUE TITLE
Current candidate is not shown for consult-buffer

### ISSUE THREAD

**Issue by minad** [oantolin/icomplete-vertical#33]
The group title hides the candidate. I think this is due to the line prefix fix in #29. See https://github.com/minad/consult/issues/278

**Comment by oantolin** [comment]
Yes, I didn't notice but newlines in line prefixes don't work: `(propertize "def" 'line-prefix "abc\n")` displays as `abc^Jdef`.

**Comment by s-kostyaev** [comment]
Thank you @oantolin @minad
