### ISSUE TITLE
Rename the package

### ISSUE THREAD

**Issue by minad** [oantolin/icomplete-vertical#36]
Now there is icomplete-vertical-mode in Emacs which is different from this package. This makes it hard to still try this package on 28. Alternatively add a note to the README and somehow mark it as "end of support"? Alternatively mark Emacs 28 as unsupported, is this possible in the dependency specification?

**Comment by oantolin** [comment]
I think renaming is probably the best strategy. I haven't tried the icomplete-vertical that's in Emacs 28, but I doubt it supports title functions. 😉 Does it show annotations and affixations?

And how does one go about renaming a package?

**Comment by minad** [comment]
I think it is better to prevent this package from being used on Emacs 28. Having both Emacs 28 icomplete-vertical and this package will only lead to conflicts.

The Emacs icomplete-vertical will get annotation/affixation support (https://debbugs.gnu.org/cgi/bugreport.cgi?bug=48013). And group function support may or may not be added depending on if the proposal is accepted.

**Comment by oantolin** [comment]
Well, I already have various completion UIs installed that don't work perfectly if you activate them at the same time as the built-in icomplete, I'm not sure one more incompatibility is really so terrible. If the package were renamed, what conflicts do you think would still arise?

If I followed your suggestion of preventing this package from being installed on Emacs 28, that would have the advantage of not requiring this package to be renamed. I guess Emacs 28 users would lose the annotations and grouping functionality, but may soon regain the annotations and possibly later even regain the grouping. My first instinct is to not cost Emacs 28 users any loss of functionality, but maybe you're right and it's not so bad if they lose a bit.

If I prevented installation on Emacs 28 I wouldn't be able to easily install this package anymore, but I guess I trust the MELPA build process by now and could continue supporting it by loading it from its source directory (I usually install my own packages to make sure the installation works too --so far this has only really helped make sure I got the autoloads and info manual generation right).

**Comment by oantolin** [comment]
By the way, I still don't understand why there is a built-in icomplete-vertical package now. Why wasn't that functionality added directly to icomplete instead?

**Comment by minad** [comment]
> If I followed your suggestion of preventing this package from being installed on Emacs 28, that would have the advantage of not requiring this package to be renamed.

Yes, I think that's the simplest solution and the best way forward. I think we will soon see annotations/affixations on Emacs 28 and then nothing is really lost for the Emacs 28 users. If there are still some corners where your package does better than the built-in mode, we can send bug reports to Emacs.

> By the way, I still don't understand why there is a built-in icomplete-vertical package now. Why wasn't that functionality added directly to icomplete instead?

There is no additional built-in package, there is only an `icomplete-vertical-mode` now.

**Comment by oantolin** [comment]
> nothing is really lost for the Emacs 28 users

I was thinking of grouping, but I guess that would only affect people simultaneously using an extremely recent Emacs 28, consult and icomplete-vertical. There can't be too many of those.

> There is no additional built-in package, there is only an icomplete-vertical-mode now.

I still don't think there should be a mode, it should be automatic when the icomplete separator contains newlines.

**Comment by minad** [comment]
> I was thinking of grouping, but I guess that would only affect people simultaneously using Emacs 28, consult and icomplete-vertical. There can't be too many of those.

Yes. And I have made this proposal to add the group-function upstream. If it is decided that this is added we will also see it in the Icomplete of Emacs 28. If it won't get in, the user who badly wants to have grouping can then decide if Icomplete is really the solution they want to use - there is also Vertico, Selectrum etc.

> I still don't think there should be a mode, it should be automatic when the icomplete separator contains newlines.

Maybe. I don't really have an opinion on this and I haven't followed the discussion on the mailing list. I think my Vertico+Corfu is a better implementation :shrug:

**Comment by oantolin** [comment]
As you know I also prefer Vertico and Selectrum to Icomplete-vertical, but they do have this weird UI that doesn't cycle through candidates and instead gets stuck at the beginning or end, so I'm not sure I'd recommend them to people used to icomplete. 😉 

A litte more seriously, Vertico is only vertical, so it's not really a substitute for Icomplete + Icomplete-vertical. Selectrum definitely is.

**Comment by oantolin** [comment]
Do you know how to mark a package as incompatible with some version of Emacs?

**Comment by minad** [comment]
> As you know, I also prefer Vertico and Selectrum to Icomplete-vertical, but they do have this weird UI that doesn't cycle through candidates and instead "helpfully" gets stuck at the beginning or end, so I'm not sure I'd recommend them to people used to icomplete.

Yeah, I wonder if there other UIs in any other programs which use rotation. There is the advantage that you only have to focus to the single point.

 > A litte more seriously, Vertico is only vertical, so it's not really a substitute for Icomplete + Icomplete-vertical. Selectrum definitely is. And Vertico is also a good replacement for people who only use icomplete vertically. But besides that I find it odd.

Indeed. I quickly tried to hack a "Horico" mode (https://github.com/minad/vertico/tree/horico), but I don't really see a reason for it (And I am saying this as a long term Ido users for many years). You lose Marginalia and my Consult commands also spit out these long candidates.

**Comment by minad** [comment]
> Do you know how to mark a package as incompatible with some version of Emacs?

No, maybe the version specification allows this. But I would have to look this up. Otherwise you could define a macro which checks at compile time if you are on emacs27 and otherwise refuse to compile.

**Comment by oantolin** [comment]
> No, maybe the version specification allows this.

It must, since at times I've seen "incompatible" in the Status column of the `*Packages*` buffer.

**Comment by oantolin** [comment]
But now that I think about it, maybe I only saw those "incompatible" statuses at the office (I have an office! after a year of working from home it's easy to forget), where I have an older Emacs version.
