### ISSUE TITLE
Minibuffer toggle mode {de,}activation produces messages that interfere with the candidates

### ISSUE THREAD

**Issue by protesilaos** [oantolin/icomplete-vertical#8]
In Emacs 27.0.90, binding `icomplete-vertical-mode` to a key in `icomplete-minibuffer-map`, will produce an echo area message whenever the mode's state is toggled. These messages can interfere with the completion candidates.

![Screenshot at 2020-04-05 06-58-32](https://user-images.githubusercontent.com/12828033/78466622-ef382080-770b-11ea-8983-8452a2fe70b6.png)

More noticeable on the horizontal view:

![Screenshot at 2020-04-05 06-58-23](https://user-images.githubusercontent.com/12828033/78466624-f65f2e80-770b-11ea-8fb9-8f7170bb15cd.png)

Whereas a toggle that specifies explicit `(icomplete-vertical-mode 1)` and `(icomplete-vertical-mode -1)` does not produce such messages.

Do you think such a toggle could be provided at the package level?

**Comment by oantolin** [comment]
Good idea! I added `icomplete-vertical-toggle` which does this.

(I had decided to just put up with this, since after all the message disappears after any keystroke, but why put up with it if it so easy to fix? Thanks for giving me the extra nudge to add the command.)

**Comment by protesilaos** [comment]
Thanks!
